run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on: push

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install prerequisites
        run: sudo apt-get install sshpass
      - name: Install environment
        run: sshpass -p ${{secrets.HOST_PASSWORD}} ssh ${{secrets.HOST_ADDRESS}} 'bash -s' < ./deploy_scripts/install.sh
      - name: Run
        run: sshpass -p ${{secrets.HOST_PASSWORD}} ssh ${{secrets.HOST_ADDRESS}} 'bash -s' < ./deploy_scripts/run.sh