run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on: push

jobs:
  test_schedule:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install
        run: |
          test -d venv || python3 -m venv venv
          source venv/bin/activate
          make install_unix

      - name: run
        run: python3 -m app