run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on: push

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install_preprequisites
        run: sudo apt-get install sshpass
      - name: install
        run: sshpass -p ${HOST_PASSWORD} ${HOST_ADDRESS} 'bash -s' < deploy_scripts/install.sh
      - name: run
        run: sshpass -p ${HOST_PASSWORD} ${HOST_ADDRESS} 'bash -s' < deploy_scripts/run.sh