run-name: Deploy to self_hosted by @${{ github.actor }}

on: push

jobs:
  test_schedule:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: docker build -t boared_app .
      - name: stop_existing
        run: docker stop $(docker ps -q --filter ancestor=boared_app ) || true
      - name: run
        run: docker run -d -p 5000:5000 boared_app